version: '3'

tasks:
  dev:
    cmds:
      - bunx @tailwindcss/cli@next -i ui/css/main.css -o ui/static/main.css
      - air

  test:
    cmds:
      - go test -v ./...

  update:
    cmds:
      - go get -u -t ./...
      - go mod tidy